### ISSUE TITLE
Programme Python

### ISSUE THREAD

**Issue by LP1412** [LP1412/Test#3]
### Discussed in https://github.com/LP1412/Test/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **LP1412** January 29, 2024</sup>
J'ai crée mon premier programme, comment je peux m'améliorer ?</div>

J'ai fait ça :
count = 1
while count <= 5:
    print(count)
    count += 1

**Comment by Thomas141203** [comment]
Oui c'est bien, en python tu peux même le faire sans à créer de variable :
for count in range(1, 6):
    print(count)
