### ISSUE TITLE
If

### ISSUE THREAD

**Issue by LP1412** [LP1412/Test#4]
J'ai teste les if pour faire ça :

age = int(input("Quel est votre âge ? "))
print("Vous êtes mineur." if age < 18 else "Vous êtes majeur." if age < 65 else "Vous êtes un sénior.")

**Comment by Thomas141203** [comment]
Oui c'est bien, je te conseille de l'écrire plus comme ça :

age = int(input("Quel est votre âge ? "))

if age < 18:
    print("Vous êtes mineur.")
elif age >= 18 and age < 65:
    print("Vous êtes majeur.")
else:
    print("Vous êtes un sénior.")

Au début c'est mieux pour que ce soit plus lisible
